[package]
name = "invade-rs"
version = "0.1.0"
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
termion = "*"
tui = "0.3.0-beta.3"
clap = "2.32.0"
